CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO tasks (id, title, done)
VALUES
    (1, 'Chore 1', FALSE),
    (2, 'Chore 2', TRUE),
    (3, 'Chore 3', TRUE);