services:
  db:
    image: postgres:17
    container_name: taskdb-compose

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - taskdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: taskapi-compose

    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}

    ports:
      - "8000:8000"

    depends_on:
      - db

volumes:
  taskdata: